# This workflow will run DVT test with existing version of Python in a virtual environment
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application_venv_RangeDVT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: activate virtual environment
      run: |
        source RangeDVT /bin/activate
        
    - name: Run the DVT
      run: |
        python3 EHref_gfprobe_tet_rev3.py
